org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=simple_fishing_overhaul
mod.name=Simple Fishing Overhaul
mod.group=me.pajic
mod.version=1.0.0
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=Fish the actual fish from the water
mod.sources_url=https://github.com/pajicadvance/simple-fishing-overhaul
mod.homepage_url=https://modrinth.com/mod/simple-fishing-overhaul
mod.issues_url=https://github.com/pajicadvance/simple-fishing-overhaul/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.parchment=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]

runtime.sodium=[VERSIONED]
runtime.fns=[VERSIONED]

publish.modrinth=
publish.curseforge=
publish.github=false
